from ..core.visual_base import VisualBase as VisualBase
from ..types.buffer import Buffer as Buffer
from ..types.group import Groups as Groups
from ..types.transbuf import TransBuf as TransBuf

class Points(VisualBase):
    def __init__(self, positions: TransBuf, sizes: TransBuf, face_colors: TransBuf, edge_colors: TransBuf, edge_widths: TransBuf, groups: Groups) -> None: ...
    def get_positions(self) -> TransBuf: ...
    def set_positions(self, positions: TransBuf) -> None: ...
    def get_sizes(self) -> TransBuf: ...
    def set_sizes(self, sizes: TransBuf) -> None: ...
    def get_face_colors(self) -> TransBuf: ...
    def set_face_colors(self, face_colors: TransBuf) -> None: ...
    def get_edge_colors(self) -> TransBuf: ...
    def set_edge_colors(self, edge_colors: TransBuf) -> None: ...
    def get_edge_widths(self) -> TransBuf: ...
    def set_edge_widths(self, edge_widths: TransBuf) -> None: ...
    def get_groups(self) -> Groups: ...
    def set_groups(self, groups: Groups) -> None: ...
    def set_attributes(self, positions: TransBuf | None = None, sizes: TransBuf | None = None, face_colors: TransBuf | None = None, edge_colors: TransBuf | None = None, edge_widths: TransBuf | None = None, groups: Groups | None = None) -> None: ...
    def check_attributes(self) -> None: ...
    @staticmethod
    def sanity_check_attributes_buffer(positions: Buffer, sizes: Buffer, face_colors: Buffer, edge_colors: Buffer, edge_widths: Buffer, groups: Groups): ...
    @staticmethod
    def sanity_check_attributes(positions: TransBuf, sizes: TransBuf, face_colors: TransBuf, edge_colors: TransBuf, edge_widths: TransBuf, groups: Groups) -> None: ...
