"""Protocol spine for GSP sessions.

This package contains transport-independent protocol models. It is designed to
coexist with the legacy object graph while the protocol layer is introduced.
"""

from .capabilities import (
    AdaptationDecision,
    AdaptationOutcome,
    AxisProviderCapability,
    AxisProviderRequest,
    CapabilitySnapshot,
    QueryOrderingGuarantee,
    QueryPlanningContext,
    QueryScopeCapability,
    QueryTargetCapability,
    QueryTargetKind,
    TransportKind,
    query_scope_for_axis_requirement,
    select_axis_provider,
)
from .commands import CommandBatch, CommandKind, ProtocolCommand
from .data_sources import (
    CredentialPolicy,
    DataLocality,
    DataSourceDescriptor,
    DataSourceKind,
    FakeTiledImageProvider,
    MaterializationPolicy,
    TileAvailability,
    TileEncoding,
    TileIndex,
    TileRequest,
    TileResult,
    TileStatus,
    TiledImageQueryPayload,
    TiledImageSource,
    ViewportMosaicResult,
    ViewportTileRequest,
)
from .extensions import (
    ExtensionKind,
    ExtensionManifest,
    ExtensionSupportLevel,
    TILED_IMAGE_EXTENSION_CAPABILITY,
    TILED_IMAGE_EXTENSION_ID,
    TILED_IMAGE_EXTENSION_VERSION,
    tiled_image_extension_manifest,
)
from .guides import (
    AxisDimension,
    AxisGuide,
    AxisSide,
    GuideQueryPolicy,
    PanelTextGuide,
    PanelTextRole,
    TickSpec,
    TickSpecKind,
)
from .ids import ObjectRef, new_id, validate_id
from .panels import AspectPolicy, Panel, View2D, VisualAttachment, VisualCoordinateSpace
from .query import (
    GUIDE_QUERY_PAYLOAD_KIND,
    GuideQueryPayload,
    QueryContributionKind,
    QueryCoordinateSpace,
    QueryHit,
    QueryHitPolicy,
    QueryPayload,
    QueryRequest,
    QueryResult,
    QueryScope,
    QueryStatus,
    VisualFamily,
)
from .resources import AttributeSource, BufferResource, ResourceLocality, ResourceMutability, ResourceUsage
from .transports import CommandResult, InProcessGSPServer, InProcessTransport, InitializeResult
from .ticks import ResolvedTicks, resolve_ticks
from .visuals import CoordinateSpace, ImageInterpolation, ImageOrigin, ImageVisual, PointVisual

__all__ = [
    "AdaptationDecision",
    "AdaptationOutcome",
    "AspectPolicy",
    "AttributeSource",
    "AxisProviderCapability",
    "AxisProviderRequest",
    "AxisDimension",
    "AxisGuide",
    "AxisSide",
    "BufferResource",
    "CapabilitySnapshot",
    "CommandBatch",
    "CommandKind",
    "CommandResult",
    "CoordinateSpace",
    "CredentialPolicy",
    "DataLocality",
    "DataSourceDescriptor",
    "DataSourceKind",
    "ImageInterpolation",
    "ImageOrigin",
    "ImageVisual",
    "ExtensionKind",
    "ExtensionManifest",
    "ExtensionSupportLevel",
    "FakeTiledImageProvider",
    "GuideQueryPolicy",
    "GUIDE_QUERY_PAYLOAD_KIND",
    "GuideQueryPayload",
    "InitializeResult",
    "InProcessGSPServer",
    "InProcessTransport",
    "MaterializationPolicy",
    "ObjectRef",
    "Panel",
    "PanelTextGuide",
    "PanelTextRole",
    "PointVisual",
    "ProtocolCommand",
    "QueryContributionKind",
    "QueryCoordinateSpace",
    "QueryHit",
    "QueryHitPolicy",
    "QueryOrderingGuarantee",
    "QueryPayload",
    "QueryPlanningContext",
    "QueryRequest",
    "QueryResult",
    "QueryScope",
    "QueryScopeCapability",
    "QueryStatus",
    "QueryTargetCapability",
    "QueryTargetKind",
    "ResourceLocality",
    "ResourceMutability",
    "ResourceUsage",
    "ResolvedTicks",
    "TILED_IMAGE_EXTENSION_CAPABILITY",
    "TILED_IMAGE_EXTENSION_ID",
    "TILED_IMAGE_EXTENSION_VERSION",
    "TileAvailability",
    "TileEncoding",
    "TileIndex",
    "TileRequest",
    "TileResult",
    "TileStatus",
    "TickSpec",
    "TickSpecKind",
    "TiledImageQueryPayload",
    "TiledImageSource",
    "TransportKind",
    "View2D",
    "ViewportMosaicResult",
    "ViewportTileRequest",
    "VisualAttachment",
    "VisualCoordinateSpace",
    "VisualFamily",
    "new_id",
    "query_scope_for_axis_requirement",
    "resolve_ticks",
    "select_axis_provider",
    "tiled_image_extension_manifest",
    "validate_id",
]
