from ..types import Buffer as Buffer, BufferType as BufferType
from .transform_link import TransformLink as TransformLink

class TransformChain:
    def __init__(self, buffer_count: int, buffer_type: BufferType | None) -> None: ...
    def is_fully_defined(self) -> bool: ...
    def get_buffer_count(self) -> int: ...
    def get_buffer_type(self) -> BufferType: ...
    def add(self, link: TransformLink) -> None: ...
    def remove(self, link: TransformLink) -> None: ...
    def run(self) -> Buffer: ...
