from ..types.transbuf import TransBuf as TransBuf
from ..utils.uuid_utils import UuidUtils as UuidUtils
from typing import Any

class Camera:
    userData: dict[str, Any]
    def __init__(self, view_matrix: TransBuf, projection_matrix: TransBuf) -> None: ...
    def get_uuid(self) -> str: ...
    def set_view_matrix(self, view_matrix: TransBuf): ...
    def get_view_matrix(self) -> TransBuf: ...
    def set_projection_matrix(self, projection_matrix: TransBuf): ...
    def get_projection_matrix(self) -> TransBuf: ...
