from ..utils.uuid_utils import UuidUtils as UuidUtils
from typing import Any

class Canvas:
    userData: dict[str, Any]
    def __init__(self, width: int, height: int, dpi: float) -> None: ...
    def get_uuid(self) -> str: ...
    def get_width(self) -> int: ...
    def get_height(self) -> int: ...
    def get_dpi(self) -> float: ...
