from ..utils.uuid_utils import UuidUtils as UuidUtils
from typing import Any

class Viewport:
    userData: dict[str, Any]
    def __init__(self, origin_x: int, origin_y: int, width: int, height: int) -> None: ...
    def get_uuid(self) -> str: ...
    def get_origin_x(self) -> int: ...
    def get_origin_y(self) -> int: ...
    def get_width(self) -> int: ...
    def get_height(self) -> int: ...
