from .buffer_type import BufferType as BufferType
from enum import Enum as Enum

class Buffer:
    def __init__(self, count: int, buffer_type: BufferType) -> None: ...
    def get_count(self) -> int: ...
    def get_type(self) -> BufferType: ...
    def get_data(self, offset: int, count: int) -> Buffer: ...
    def set_data(self, _bytearray: bytearray, offset: int, count: int) -> None: ...
    def to_bytearray(self) -> bytearray: ...
    @staticmethod
    def from_bytearray(_bytearray: bytearray, buffer_type: BufferType) -> Buffer: ...
