from typing import Any, Union, Sequence
from enum import Enum

# =============================================================================
# Buffer
# =============================================================================
class BufferType(Enum):
    float32 = 0
    uint32 = 1
    uint8 = 2
    int32 = 3
    int8 = 4
    vec2 = 5
    vec3 = 6
    vec4 = 7
    mat4 = 8
    rgba8 = 9

class Buffer:
    def __init__(self, count: int, buffer_type: BufferType) -> None: ...
    def get_count(self) -> int: ...
    def get_type(self) -> BufferType: ...
    def get_data(self, offset: int, count: int) -> Buffer: ...
    def set_data(self, _bytearray: bytearray, offset: int, count: int) -> None: ...
    def to_bytearray(self) -> bytearray: ...
    @staticmethod
    def from_bytearray(_bytearray: bytearray, buffer_type: BufferType) -> Buffer: ...

# =============================================================================
# Transform placeholder
# =============================================================================
class TransformChain: ...

# =============================================================================
# TransBuf type
# =============================================================================

TransBuf = TransformChain | Buffer
"""A type that can be either a TransformChain or a Buffer."""

# =============================================================================
# Groups
# =============================================================================
Groups = Union[int, list[int], list[list[int]]]
"""A type that can represent group IDs in various forms."""

# =============================================================================
# Canvas/Viewport
# =============================================================================

class Canvas:
    userData: dict[str, Any]
    """userData is a dictionary for storing custom user data."""
    def __init__(self, width: int, height: int, dpi: float) -> None: ...
    def get_uuid(self) -> str: ...
    def get_width(self) -> int: ...
    def get_height(self) -> int: ...
    def get_dpi(self) -> float: ...

class Viewport:
    userData: dict[str, Any]
    """userData is a dictionary for storing custom user data."""
    def __init__(self, origin_x: int, origin_y: int, width: int, height: int) -> None: ...
    def get_uuid(self) -> str: ...
    def get_origin_x(self) -> int: ...
    def get_origin_y(self) -> int: ...
    def get_width(self) -> int: ...
    def get_height(self) -> int: ...

# =============================================================================
# Visuals
# =============================================================================

class VisualBase:
    userData: dict[str, Any]
    """userData is a dictionary for storing custom user data."""
    def __init__(self) -> None: ...
    def get_uuid(self) -> str: ...

class Pixels(VisualBase):
    def __init__(self, positions: TransBuf, colors: TransBuf, groups: Groups) -> None: ...
    def get_positions(self) -> TransBuf: ...
    def set_positions(self, positions: TransBuf) -> None: ...
    def get_colors(self) -> TransBuf: ...
    def set_colors(self, colors: TransBuf) -> None: ...
    def get_groups(self) -> Groups: ...
    def set_groups(self, groups: Groups) -> None: ...
    def set_attributes(self, positions: TransBuf | None = None, colors: TransBuf | None = None, groups: Groups | None = None) -> None: ...

# =============================================================================
# Rendering
# =============================================================================

class Camera:
    userData: dict[str, Any]
    """userData is a dictionary for storing custom user data."""
    def __init__(self, view_matrix: TransBuf, projection_matrix: TransBuf) -> None: ...
    def get_uuid(self) -> str: ...
    def set_view_matrix(self, view_matrix: TransBuf): ...
    def get_view_matrix(self) -> TransBuf: ...
    def set_projection_matrix(self, projection_matrix: TransBuf): ...
    def get_projection_matrix(self) -> TransBuf: ...

class MatplotlibRenderer:
    def __init__(self, canvas: Canvas) -> None: ...
    def render(self, viewports: Sequence[Viewport], visuals: Sequence[VisualBase], model_matrices: Sequence[TransBuf], cameras: Sequence[Camera]): ...
